import json
from datetime import datetime
from typing import List, Dict

class ReportService:
    @staticmethod
    def generate_markdown_report(analysis_data: Dict) -> str:
        """Generate a professional markdown audit report."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        md = f"""# AetherGuard Security Audit Report
Generated on: {timestamp}
Overall Security Score: **{analysis_data.get('score', 0)}/100**
Risk Level: **{analysis_data.get('severity', 'Unknown').upper()}**

---

## 🛡️ Executive Summary
{analysis_data.get('summary', 'Detailed analysis of the smart contract.')}

## 📊 Vitals
- **Confidence Score:** {analysis_data.get('confidence', 0) * 100:.1f}%
- **Total Issues Found:** {len(analysis_data.get('findings', []))}
- **Target Language:** {analysis_data.get('findings', [{}])[0].get('language', 'Solidity').capitalize() if analysis_data.get('findings') else 'Unknown'}

---

## 🔍 Detailed Findings

"""
        for finding in analysis_data.get('findings', []):
            md += f"### [{finding.get('severity', 'info').upper()}] {finding.get('label', 'Vulnerability')}\n"
            md += f"- **ID:** `{finding.get('slug', 'unknown')}`\n"
            md += f"- **Lines:** {', '.join(map(str, finding.get('line_numbers', []))) or 'Global'}\n"
            md += f"- **Description:** {finding.get('summary', 'No description provided.')}\n"
            md += f"- **Recommendation:** {finding.get('recommendation', 'No recommendation provided.')}\n"
            md += "\n"

        md += """---

## 💡 AI Remediation Suggestions
"""
        for suggestion in analysis_data.get('fix_suggestions', []):
            md += f"- {suggestion}\n"

        md += f"\n### 🛠️ Proposed Secure Rewrite\n```solidity\n{analysis_data.get('fix', '// No fix provided.')}\n```\n"
        
        md += """
---
*Disclaimer: This report is generated by AetherGuard AI and should be used as a tool to assist manual audits. Use in production at your own risk.*
"""
        return md

    @staticmethod
    def generate_json_report(analysis_data: Dict) -> str:
        """Return raw JSON report."""
        return json.dumps(analysis_data, indent=2)
