"""Rename subscription_plan to plan and add scans_used

Revision ID: f37bf282bacf
Revises: abff0117cf75
Create Date: 2026-04-01 19:49:59.831485
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'f37bf282bacf'
down_revision = 'abff0117cf75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.Text(), server_default='free', nullable=False))
        batch_op.add_column(sa.Column('scans_used', sa.Integer(), server_default='0', nullable=False))
        batch_op.drop_column('subscription_plan')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan', sa.TEXT(), server_default=sa.text("'free'"), nullable=False))
        batch_op.drop_column('scans_used')
        batch_op.drop_column('plan')

    # ### end Alembic commands ###
